<a href="https://colab.research.google.com/github/NguyenTanTan/Bai-tap-python/blob/python/B2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1 - Ma trận: Trong Toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối
tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu
là A ∈ Rm×n hay Am×n hay A = (ai,j)
m×n
A = [
a1,1
a1,2 ⋯ a1,n
a2,1
⋮
a2,2 ⋯
⋮ ⋮
a2,n
⋮

am,1
am,2 ⋯ am,n
]
Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
import numpy as np
import random
mat_=[]
# Sinh ngẫu nhiên các giá trị của ma trận
for i in range(0,7):
  a=np.array([random.randint(0,10)for i in range(0,5)])
  mat_.append(a)
print(mat_)
# Tạo ma trận 7x5:
mat=np.matrix(mat_)
print(mat)

[array([8, 2, 5, 8, 5]), array([4, 3, 9, 5, 5]), array([10,  9,  2, 10,  7]), array([0, 1, 3, 6, 4]), array([9, 3, 9, 3, 4]), array([ 5, 10,  9,  8,  7]), array([ 0,  6,  2,  1, 10])]
[[ 8  2  5  8  5]
 [ 4  3  9  5  5]
 [10  9  2 10  7]
 [ 0  1  3  6  4]
 [ 9  3  9  3  4]
 [ 5 10  9  8  7]
 [ 0  6  2  1 10]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [ ]:
import numpy as np
a=np.zeros((6,7),int)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ R7×7

, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả

xuất ra màn hình.

In [ ]:
import numpy as np
import random
# Tạo giá trị ngẫu nhiên 
ma=[]
for i in range(0,7):
  a=np.array([random.randint(0,10)for i in range(0,7)])
  ma.append(a)
print(ma)
# Tạo ma trận vuông 7x7:
matr=np.matrix(ma)
print(matr)


[array([ 8,  9,  5,  1, 10,  4,  9]), array([ 5,  8,  2,  9, 10,  9,  8]), array([8, 6, 0, 1, 4, 0, 5]), array([7, 3, 7, 5, 6, 3, 7]), array([ 1,  2,  1,  3,  0,  5, 10]), array([ 2,  9, 10,  4,  6,  1,  0]), array([8, 4, 3, 1, 0, 0, 2])]
[[ 8  9  5  1 10  4  9]
 [ 5  8  2  9 10  9  8]
 [ 8  6  0  1  4  0  5]
 [ 7  3  7  5  6  3  7]
 [ 1  2  1  3  0  5 10]
 [ 2  9 10  4  6  1  0]
 [ 8  4  3  1  0  0  2]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0
trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá
trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra
màn hình.

In [ ]:
import numpy as np
# Tạo ma trận 0 :
ma0=np.zeros((6,6),int)
print(ma0)
# Tạo ma trận chéo:
np.fill_diagonal(ma0,15)
print(" Ma trận chéo: ",ma0)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
 Ma trận chéo:  [[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm
numpy.triu(). Kết quả xuất ra màn hình.

In [ ]:
import numpy as np
# Tạo ma trận tam giác trên
matu=np.triu(np.arange(64).reshape(8, 8),0) # np.triu: các phần tử dưới đường chéo 0 trả về giá trị 0.
print(" Ma trận tam giác trên: \n",matu)




 Ma trận tam giác trên: 
 [[ 0  1  2  3  4  5  6  7]
 [ 0  9 10 11 12 13 14 15]
 [ 0  0 18 19 20 21 22 23]
 [ 0  0  0 27 28 29 30 31]
 [ 0  0  0  0 36 37 38 39]
 [ 0  0  0  0  0 45 46 47]
 [ 0  0  0  0  0  0 54 55]
 [ 0  0  0  0  0  0  0 63]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [ ]:
import numpy as np
# Tạo ma trận tam giác dưới
matd=np.tril(np.arange(64).reshape(8, 8),0) 
print(" Ma trận tam giác trên: \n",matd)




 Ma trận tam giác trên: 
 [[ 0  0  0  0  0  0  0  0]
 [ 8  9  0  0  0  0  0  0]
 [16 17 18  0  0  0  0  0]
 [24 25 26 27  0  0  0  0]
 [32 33 34 35 36  0  0  0]
 [40 41 42 43 44 45  0  0]
 [48 49 50 51 52 53 54  0]
 [56 57 58 59 60 61 62 63]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [1]:
import numpy as np
print(np.identity(9))

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:
 Phép cộng ma trận: Am×n + Bm×n = Cm×n. Hãy sinh ngẫu nhiên 2 ma trận có kích thước
6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.
 Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 1 ma trận có kích thước
5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất
ra màn hình.
 Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.
 Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()
 Ma trận khả nghịch: ma trận vuông An×n gọi là khả nghịch (hay không suy biến) nếu tồn
tại một ma trận vuông Bn×n sao cho A ∙ B = In . Khi này, B được gọi là ma trận nghịch
đảo của A và ký hiệu là A
−1
. Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi

ý: sử dụng hàm numpy.linalg.inv()

In [23]:
import numpy as np
import random
# Tạo ngẫu nhiên 2 ma trận 6x7:
mat1=np.array([random.randint(0,20) for i in range(0,42)]).reshape((6,7))
mat2=np.array([random.randint(0,20) for i in range(0,42)]).reshape((6,7))
print("Ma trận 1:\n",mat1)
print("Ma trận 2:\n",mat2)
# Cộng 2 ma trận:
summa=mat1+mat2
print("Tổng 2 ma trận:\n", summa)



Ma trận 1:
 [[11 19 15  4  1  0  4]
 [18  2 19 20  2 14 13]
 [13  1 17 17  5 14 19]
 [12 12  6 15 17 20 17]
 [18  9  1  2  9 17  4]
 [20  1  9  1 17  8 13]]
Ma trận 2:
 [[ 4  1  6 12  8  9  7]
 [ 7 17  6  0  6 10 20]
 [ 1 14  6 20  4  8 17]
 [ 3  8  4 15 12 13  8]
 [19  4 17 20 10  3  1]
 [20  8 16 13 14  4  8]]
Tổng 2 ma trận:
 [[15 20 21 16  9  9 11]
 [25 19 25 20  8 24 33]
 [14 15 23 37  9 22 36]
 [15 20 10 30 29 33 25]
 [37 13 18 22 19 20  5]
 [40  9 25 14 31 12 21]]


In [12]:
# Tạo ngẫu nhiên ma trận 5x8:
mat3=np.array([random.randint(0,20) for i in range(0,40)]).reshape((5,8))
print("Ma trận 3:\n",mat3)
# Nhập một sô từ bàn phím:
n=int(input(" Nhập một số từ bàn phím: "))
# Nhân vô hướng với ma trận:
print(" Kết quả nhân vô hướng với ma trận:\n", mat3*n)

Ma trận 3:
 [[13  9 12 11  2 12 17  0]
 [15 13  4  5  8  4 10  1]
 [ 5 17 10 20  0 20 15  1]
 [16 15 16  6  3 15 12 18]
 [ 3  0 19  4  7 13  3 13]]
 Nhập một số từ bàn phím: 2
 Kết quả nhân vô hướng với ma trận:
 [[26 18 24 22  4 24 34  0]
 [30 26  8 10 16  8 20  2]
 [10 34 20 40  0 40 30  2]
 [32 30 32 12  6 30 24 36]
 [ 6  0 38  8 14 26  6 26]]


In [14]:
# Tạo ngẫu nhiên ma trận 3x7:
mat4=np.array([random.randint(0,20) for i in range(0,21)]).reshape((3,7))
print("Ma trận 3x7:\n",mat4)
# Chuyển vị ma trận:
print(" Ma trận chuyển vị:\n", mat4.T)


Ma trận 3x7:
 [[18 15 12 10 18 16  6]
 [16  7 11 13  4 13  4]
 [ 9 20  5 18 20  3  2]]
 Ma trận chuyển vị:
 [[18 16  9]
 [15  7 20]
 [12 11  5]
 [10 13 18]
 [18  4 20]
 [16 13  3]
 [ 6  4  2]]


In [18]:
# Tạo 2 ma trận 5x7 và 7x3
mat5=np.array([random.randint(0,20) for i in range(0,35)]).reshape((5,7))
mat6=np.array([random.randint(0,20) for i in range(0,21)]).reshape((7,3))
print(" Ma trận 5x7:\n",mat5)
print(" Ma trận 7x3:\n",mat6)
# Nhân 2 ma trận:
mat7=np.dot(mat5,mat6)
print("Kết quả nhân 2 ma trận:\n",mat7)


 Ma trận 5x7:
 [[18  8 17 13  6 17 14]
 [ 6 11 11  5  5 18  5]
 [12 16  3 20 12 16  2]
 [12 12  4 16  7 14  9]
 [ 0 14  6  6 13 14 16]]
 Ma trận 7x3:
 [[ 6 18 12]
 [14  1 12]
 [18  1  7]
 [12 17 19]
 [11  2  4]
 [14 11 18]
 [13  5  7]]
Kết quả nhân 2 ma trận:
 [[1168  839 1106]
 [ 820  448  755]
 [ 972  785 1087]
 [ 894  717  963]
 [ 923  382  740]]


In [42]:
# Tạo ma trận 5x5:
mat7=np.array([random.randint(0,20) for i in range(0,25)]).reshape((5,5))
print(mat7)
# Ma trận khả nghịch:
mat7iv=np.linalg.inv(mat7)
print("Ma trận khả nghịch:\n",mat7iv)

[[11  3  7  0 17]
 [14 15  2 16  2]
 [ 5 10  3 18  7]
 [ 3 16 16 13 16]
 [11 14  8 20  5]]
Ma trận khả nghịch:
 [[ 0.04381437  0.01046035 -0.05580097 -0.04583695  0.07164661]
 [-0.04197378  0.14206064 -0.01168052  0.08053936 -0.15548662]
 [-0.00207635 -0.09565289 -0.11488605  0.01029077  0.17323076]
 [-0.00356951 -0.06882161  0.06345287 -0.03808578  0.07270546]
 [ 0.03873516  0.0075485   0.0854738   0.011209   -0.09025107]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau
 Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1
vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
 Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [37]:
import numpy as np
# Tạo vector :
vecrow=np.matrix(np.arange(8).reshape((1,8)))
veccol=np.matrix(np.arange(8).reshape((8,1)))
print(" Vector hàng:\n",vecrow)
print(" Vector cột:\n",veccol)

 Vector hàng:
 [[0 1 2 3 4 5 6 7]]
 Vector cột:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


Bài 10 - Hệ phương trình tuyến tính: Xét hệ phương trình tuyến tính sau:

{
a1,1x1 + a1,2x2 + ... + a1,nxn = b1
a2,1x1 + a2,2x2 + ... + a2,nxn = b2

⋮

am,1x1 + am,2x2 + ... + am,nxn = bm

Có thể được viết lại dưới cú pháp ma trận như sau:
Am×n ∙ xn×1 = bm×1

Khi đó, nếu A là ma trận khả nghịch thì hệ phương trình trên có nghiệm là x = A
−1b.

Dựa vào tóm tắt lý thuyết nêu trên, bạn hãy xây dựng chương trình Python sử dụng thư viện
NumPy để giải hệ phương trình tuyến tính.

In [53]:
import numpy as np
import random
# Nhập số biến và số phương trình
n=int(input(" Cấp của ma trận vuông: "))
# Tạo ma trận hệ số
maths=np.matrix([random.randint(1,20) for i in range(0,n*n)]).reshape(n,n)
print("Ma trận hệ số:\n",maths)
# Tạo vector vế phải b:
matb=np.matrix([random.randint(1,20) for i in range(0,n)]).reshape(n,1)
print("Vector vế phải b:\n",matb)

# Giải hệ phương trình:
x=np.linalg.solve(maths,matb)
print("Kết quả:\n",x)


 Cấp của ma trận vuông: 4
Ma trận hệ số:
 [[14  2  3 20]
 [ 8  1 10 13]
 [16 11 13 18]
 [ 3  7  1  5]]
Vector vế phải b:
 [[ 6]
 [ 3]
 [ 4]
 [15]]
Kết quả:
 [[-3.67100921]
 [ 1.81552892]
 [-0.54577037]
 [ 2.77001911]]
