<a href="https://colab.research.google.com/github/NguyenTanTan/Bai-tap-python/blob/python/B4_NUMPY3_apply_along_axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Câu1:** Hãy trình bày cú pháp của hàm ***apply_along_axis()*** và ý nghĩa của từng tham số của hàm này.

**Cú pháp:**

*numpy.apply_along_axis(func_1D,axis,arr,args,kwargs)*

**Chức năng**

* Áp dụng một hàm cho các lát cắt 1-D dọc theo trục đã cho.
* Thực thi func_1D (a,  args,  kwargs) trong đó func_1D hoạt động trên mảng 1-D và a là lát 1-D của arr dọc theo trục .

**Các tham số:**
* func_1D: Hàm được áp dụng cho các mảng 1-D được chỉ định
* axis: Thực hiện hàm theo trục dọc hay trục ngang
* arr: Mảng thực hiện 
* args: Bổ sung đối số cho hàm
* kwargs: Bổ sung các đối số  tên cho hàm
 


**Ví dụ:**

In [10]:

import numpy as np
# Xây dựng hàm tính tổng cho mảng 1-D
def tinhtong(a):
  sum=0
  for i in a:
    sum+=i
  return sum
# Tạo một ma trận
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Ma trận:\n",arr)
# Tính tổng theo mảng chỉ định
print(" Kết quả thực hiện hàm theo các mảng chỉ định:")
print(np.apply_along_axis(tinhtong,0,arr)) # 0: tính theo cột, 1: tính theo hàng


Ma trận:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 Thực hiện hàm theo các mảng chỉ định:
[12 15 18]


**Câu 2: Tạo một ma trận $A_{15\times17}$ có giá trị ngẫu nhiên**

In [14]:
import numpy as np
import random
# Tạo ma trận ngẫu nhiên
A=np.array([random.randint(0,10) for i in range(255)]).reshape((15,17))
print(A)

[[ 8  4  1  8  1  1  2  3  0  9  3  4  1  5  6  9  0]
 [ 2  5  2  9  9  7  2  2  2  1  7  6  8 10  9  1  6]
 [ 0  3  8  8  3  9  7  9 10  7  0  7 10  6  7  5  7]
 [ 4 10  0  5  8  4  9  2  2  7  5  1  0  6  8  8  0]
 [ 3  2  3  4  0  1 10  0 10  6  1  1 10  1  6  7  0]
 [ 1  2  1 10  1  1  9  7 10  4  1  1 10  0  2  1  0]
 [ 4  9  3  1  3  0  8  9  2  7  4  3  7  9  3  4  7]
 [ 2  9  8 10  8  5  9  5  9 10  7  6  7  7  7  6  3]
 [ 2  6  6  7  0  0  7 10  0  1  4  8  9  1  6  2  6]
 [10  7  6  7  4  4  9  5  3  3  4  8  9  8  9 10  0]
 [ 9  0 10  1  8  4  6  3  6  6 10  6  7  6  9  3  6]
 [ 3  6  5  3  3  7  7  5  0  0  6  7  5 10  8  2  0]
 [ 0  4  1 10  2  0  4  1  5  3  0  8  6  4  2  4  2]
 [ 0  0  5  8  4  7  7 10  9 10  6  9  9  5  7  9  5]
 [ 3  6  9  0  0  2  3 10  1 10 10 10  5  2  8  2  1]]


**Câu 3:** Xây dựng hàm tìm giá trị lớn nhất có tên là ***tim_gia_tri_lon_nhat(vector_a)*** có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này theo từng **hàng** của ma trận **A** ở **Câu 1** và xuất kết quả ra màn hình.

In [27]:
# Xây dựng hàm tìm giá trị lớn nhất
def find_max(arr):
  max=0
  for i in arr:
    if max < i:
      max=i
    else:
      max=max
  return max

In [28]:
import numpy as np
# Áp dụng hàm vào ma trận A theo hàng:
print(np.apply_along_axis(find_max,1,A))

[ 9 10 10 10 10 10  9 10 10 10 10 10 10 10 10]


**Câu 4:** Xây dựng hàm tìm giá trị nhỏ nhất có tên là ***tim_gia_tri_nho_nhat(vector_a)*** có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng **cột** của ma trận **A** ở **Câu 1** và xuất kết quả ra màn hình.

In [30]:
# Xây dựng hàm tìm giá trị nhỏ nhất
def find_min(arr):
  min=10
  for i in arr:
    if min > i:
      min=i
    else:
      min=min
  return min

In [31]:
import numpy as np
# Áp dụng hàm vào ma trận A theo cột:
print(np.apply_along_axis(find_min,0,A))

[0 0 0 0 0 0 2 0 0 0 0 1 0 0 2 1 0]


**Câu 5:** Xây dựng hàm tính tổng có tên là ***tinh_tong(vector_a)*** có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận **A** ở **Câu 1** và xuất kết quả ra màn hình.

In [33]:
# Xây dựng hàm tính tổng:
def sum_A(arr):
  sum=0
  for i in arr:
    sum+=i
  return sum

In [34]:
import numpy as np
# Áp dụng hàm tính tổng theo từng hàng của ma trận A:
print(np.apply_along_axis(sum_A,1,A))

[ 65  88 106  79  65  61  83 118  75 106 100  77  56 110  82]


**Câu 6:** Xây dựng hàm tìm giá trị lớn nhất có tên là ***tinh_tong_2(vector_a)*** có tham số đầu vào là 1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp dụng hàm này theo từng **cột** của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng hàm này theo từng **hàng** của ma trận A kể trên và xuất kết quả ra màn hình.

In [38]:
import numpy as np
# Tạo hàm  xác định các phần tử có giá trị chỉ số lẻ
def sum_oddindex(arr):
  sum=0
  for i in range(0,len(arr)): # lặp để kiểm tra chỉ số lẻ theo chỉ số dương
    if i%2!=0:
	    sum+= arr[i]
      
  for i in range(-len(arr),-1): # lặp để kiểm tra chỉ số lẻ theo chỉ số âm
    if i%2!=0:
      sum+=arr[i]
  return sum


In [39]:
# Áp dụng theo hàng
print(np.apply_along_axis(sum_oddindex,1,A))


[ 65  82  99  79  65  61  76 115  69 106  94  77  54 105  81]


In [40]:
# Áp dụng theo cột
print(np.apply_along_axis(sum_oddindex,0,A))


[48 67 59 91 54 50 96 71 68 74 58 75 98 78 89 71 42]
