<a href="https://colab.research.google.com/github/NguyenTanTan/Bai-tap-python/blob/python/B5_NUMPY4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Câu 1:** Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [ ]:
import numpy as np
# Tạo vector a có 7 chiều với np.arange():
veca1=np.arange(0,7).reshape(1,7)
print("Vector a tạo bằng np.range():\n",veca1)
print("Số chiều của vetor:",veca1.ndim)
print("Kích thước của vector:",veca1.shape)
print("Số chiều của vetor chuyển vị:",veca1.T.ndim)
print("Kích thước của vector chuyển vị:",veca1.T.shape)



Vector a tạo bằng np.range():
 [[0 1 2 3 4 5 6]]
Số chiều của vetor: 2
Kích thước của vector: (1, 7)
Số chiều của vetor chuyển vị: 2
Kích thước của vector chuyển vị: (7, 1)


In [ ]:
# Tạo vector a có 7 chiều với np.linspace():
veca2=np.linspace(1,7,7).reshape(1,7)
print("Vector a tạo bằng np.linspace:\n",veca2)
print("Số chiều của vetor:",veca2.ndim)
print("Kích thước của vector:",veca2.shape)
print("Số chiều của vetor chuyển vị:",veca2.T.ndim)
print("Kích thước của vector chuyển vị:",veca2.T.shape)



Vector a tạo bằng np.linspace:
 [[1. 2. 3. 4. 5. 6. 7.]]
Số chiều của vetor: 2
Kích thước của vector: (1, 7)
Số chiều của vetor chuyển vị: 2
Kích thước của vector chuyển vị: (7, 1)


In [ ]:
# Tạo vector a có 7 chiều với np.logspace():
veca3=np.logspace(1,7,7).reshape(1,7)
print("Vector a tạo bằng np.logspace:\n",veca3)
print("Số chiều của vetor:",veca3.ndim)
print("Kích thước của vector:",veca3.shape)
print("Số chiều của vetor chuyển vị:",veca3.T.ndim)
print("Kích thước của vector chuyển vị:",veca3.T.shape)


Vector a tạo bằng np.logspace:
 [[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07]]
Số chiều của vetor: 2
Kích thước của vector: (1, 7)
Số chiều của vetor chuyển vị: 2
Kích thước của vector chuyển vị: (7, 1)


In [ ]:
# Tạo vector a có 7 chiều với np.random.rand():
veca4=np.random.rand(1,7)
print("Vector a tạo bằng np.random.rand():\n",veca4)
print("Số chiều của vetor:",veca4.ndim)
print("Kích thước của vector:",veca4.shape)
print("Số chiều của vetor chuyển vị:",veca4.T.ndim)
print("Kích thước của vector chuyển vị:",veca4.T.shape)
print()

veca5=np.random.randint(1,7,7)
# Tạo vector a có 7 chiều với np.random.randint():
print("Vector a tạo bằng np.random.randint():\n",veca5)
print("Số chiều của vetor:",veca5.ndim)
print("Kích thước của vector:",veca5.shape)
print("Số chiều của vetor chuyển vị:",veca5.T.ndim)
print("Kích thước của vector chuyển vị:",veca5.T.shape)

Vector a tạo bằng np.random.rand():
 [[0.32327591 0.76952928 0.97771443 0.71618997 0.05485739 0.71536136
  0.65328594]]
Số chiều của vetor: 2
Kích thước của vector: (1, 7)
Số chiều của vetor chuyển vị: 2
Kích thước của vector chuyển vị: (7, 1)

Vector a tạo bằng np.random.randint():
 [4 3 4 3 4 4 6]
Số chiều của vetor: 1
Kích thước của vector: (7,)
Số chiều của vetor chuyển vị: 1
Kích thước của vector chuyển vị: (7,)


**Câu 2:** Sử dụng thư viện Numpy, hãy tạo ra ma trận $A_{10\times7}$ với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()
Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận A và ma trận $A^T$

In [ ]:
import numpy as np
# Tạo ma trận A (10x7)  np.arange():
A1=np.arange(0,70).reshape(10,7)
print("Ma trận A tạo bằng np.range():\n",A1)
print("Số chiều của ma trận:",A1.ndim)
print("Kích thước của ma trận:",A1.shape)
print("Số chiều của ma trận chuyển vị:",A1.T.ndim)
print("Kích thước của ma trận chuyển vị:",A1.T.shape)

Ma trận A tạo bằng np.range():
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
Số chiều của ma trận: 2
Kích thước của ma trận: (10, 7)
Số chiều của ma trận chuyển vị: 2
Kích thước của ma trận chuyển vị: (7, 10)


In [ ]:
# Tạo ma trận A (10x7)  np.linspace():
A2=np.linspace(1,70,70).reshape(10,7)
print("Ma trận A tạo bằng np.linspace():\n",A2)
print("Số chiều của ma trận:",A2.ndim)
print("Kích thước của ma trận:",A2.shape)
print("Số chiều của ma trận chuyển vị:",A2.T.ndim)
print("Kích thước của ma trận chuyển vị:",A2.T.shape)

Ma trận A tạo bằng np.linspace():
 [[ 1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27. 28.]
 [29. 30. 31. 32. 33. 34. 35.]
 [36. 37. 38. 39. 40. 41. 42.]
 [43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63.]
 [64. 65. 66. 67. 68. 69. 70.]]
Số chiều của ma trận: 2
Kích thước của ma trận: (10, 7)
Số chiều của ma trận chuyển vị: 2
Kích thước của ma trận chuyển vị: (7, 10)


In [ ]:
# Tạo ma trận A (10x7)  np.logspace():
A3=np.logspace(1,70,70).reshape(10,7)
print("Ma trận A tạo bằng np.logspace():\n",A3)
print("Số chiều của ma trận:",A3.ndim)
print("Kích thước của ma trận:",A3.shape)
print("Số chiều của ma trận chuyển vị:",A3.T.ndim)
print("Kích thước của ma trận chuyển vị:",A3.T.shape)

Ma trận A tạo bằng np.logspace():
 [[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07]
 [1.e+08 1.e+09 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14]
 [1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20 1.e+21]
 [1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28]
 [1.e+29 1.e+30 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35]
 [1.e+36 1.e+37 1.e+38 1.e+39 1.e+40 1.e+41 1.e+42]
 [1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49]
 [1.e+50 1.e+51 1.e+52 1.e+53 1.e+54 1.e+55 1.e+56]
 [1.e+57 1.e+58 1.e+59 1.e+60 1.e+61 1.e+62 1.e+63]
 [1.e+64 1.e+65 1.e+66 1.e+67 1.e+68 1.e+69 1.e+70]]
Số chiều của ma trận: 2
Kích thước của ma trận: (10, 7)
Số chiều của ma trận chuyển vị: 2
Kích thước của ma trận chuyển vị: (7, 10)


In [ ]:
# Tạo ma trận A (10x7) với np.random.rand():
A4=np.random.rand(10,7)
print("Ma trận A tạo bằng np.random.rand():\n",A4)
print("Số chiều của ma trận:",A4.ndim)
print("Kích thước của ma trận:",A4.shape)
print("Số chiều của ma trận chuyển vị:",A4.T.ndim)
print("Kích thước của ma trận chuyển vị:",A4.T.shape)
print()

A5=np.random.randint(1,10,(10,7))
# Tạo ma trận A (10x7) với np.random.randint():
print("Ma trận A tạo bằng np.random.randint():\n",A5)
print("Số chiều của ma trận:",A5.ndim)
print("Kích thước của ma trận:",A5.shape)
print("Số chiều của ma trận chuyển vị:",A5.T.ndim)
print("Kích thước của  ma trận chuyển vị:",A5.T.shape)

Ma trận A tạo bằng np.random.rand():
 [[0.74447945 0.19035847 0.2427526  0.907891   0.44970608 0.02887786
  0.47793027]
 [0.02524949 0.79817762 0.73700321 0.51828207 0.95337973 0.8047741
  0.29914206]
 [0.74296339 0.36129459 0.32391505 0.03144594 0.2349968  0.3812286
  0.01565588]
 [0.93317866 0.83889719 0.64954958 0.68593881 0.62579263 0.49076481
  0.99923949]
 [0.89010033 0.63818303 0.75398043 0.74266293 0.26311001 0.93125652
  0.13381252]
 [0.3794843  0.57022048 0.66148692 0.96986723 0.986262   0.93020627
  0.74658131]
 [0.36382231 0.61396111 0.14281329 0.13009613 0.41408532 0.91076891
  0.4829733 ]
 [0.28960266 0.11045321 0.97117528 0.97019184 0.79741698 0.83214673
  0.20009038]
 [0.50832213 0.43851072 0.65033335 0.13730849 0.74853533 0.09257751
  0.08038432]
 [0.4801256  0.59190471 0.29692439 0.04834399 0.57813751 0.04867337
  0.581447  ]]
Số chiều của ma trận: 2
Kích thước của ma trận: (10, 7)
Số chiều của ma trận chuyển vị: 2
Kích thước của ma trận chuyển vị: (7, 10)

Ma trận A 

**Câu 3:** Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm ***flatten()***)
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm ***reshape()***)

In [ ]:
# Chuyển ma trận A1 thành vector:
vecA=A1.flatten()
print("Ma trận A chuyển thành một vector:")
print(vecA)

Ma trận A chuyển thành một vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [ ]:
# Chuyển vector vecA thành ma trận
A_T=vecA.reshape(7,10)
print("Vector vecA được chuyển lại thành ma trận (7x10):")
print(A_T)

Vector vecA được chuyển lại thành ma trận (7x10):
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


**Câu 4:** Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận **$A_{10\times15}$** với các giá trị được sinh ra bởi hàm **logspace()**;
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [ ]:
# Tạo ma trận A với hàm logspace:
import numpy as np
A=np.logspace(1,150,150).reshape(10,15)
print("Ma trận A tạo từ logspae():")
print(A)

Ma trận A tạo từ logspae():
[[1.e+001 1.e+002 1.e+003 1.e+004 1.e+005 1.e+006 1.e+007 1.e+008 1.e+009
  1.e+010 1.e+011 1.e+012 1.e+013 1.e+014 1.e+015]
 [1.e+016 1.e+017 1.e+018 1.e+019 1.e+020 1.e+021 1.e+022 1.e+023 1.e+024
  1.e+025 1.e+026 1.e+027 1.e+028 1.e+029 1.e+030]
 [1.e+031 1.e+032 1.e+033 1.e+034 1.e+035 1.e+036 1.e+037 1.e+038 1.e+039
  1.e+040 1.e+041 1.e+042 1.e+043 1.e+044 1.e+045]
 [1.e+046 1.e+047 1.e+048 1.e+049 1.e+050 1.e+051 1.e+052 1.e+053 1.e+054
  1.e+055 1.e+056 1.e+057 1.e+058 1.e+059 1.e+060]
 [1.e+061 1.e+062 1.e+063 1.e+064 1.e+065 1.e+066 1.e+067 1.e+068 1.e+069
  1.e+070 1.e+071 1.e+072 1.e+073 1.e+074 1.e+075]
 [1.e+076 1.e+077 1.e+078 1.e+079 1.e+080 1.e+081 1.e+082 1.e+083 1.e+084
  1.e+085 1.e+086 1.e+087 1.e+088 1.e+089 1.e+090]
 [1.e+091 1.e+092 1.e+093 1.e+094 1.e+095 1.e+096 1.e+097 1.e+098 1.e+099
  1.e+100 1.e+101 1.e+102 1.e+103 1.e+104 1.e+105]
 [1.e+106 1.e+107 1.e+108 1.e+109 1.e+110 1.e+111 1.e+112 1.e+113 1.e+114
  1.e+115 1.e+116 1.e+1

In [ ]:
# Rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng)
A_row3=A[2,:]
print(A_row3)
print("Kích thước của vector:",A_row3.shape)

[1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45]
Kích thước của vector: (15,)


In [ ]:
# Rút cột thứ 5 của ma trận A (tương ứng với 1 vector cột)
A_col5=A[:,4]
print(A_col5)
print("Kích thước của vector:",A_col5.shape)

[1.e+005 1.e+020 1.e+035 1.e+050 1.e+065 1.e+080 1.e+095 1.e+110 1.e+125
 1.e+140]
Kích thước của vector: (10,)


**Câu 5:** Thực hiện các yêu cầu sau:

- Xây dựng hàm tính giá trị trung bình

In [2]:
# Hàm tính giá trị trung bình
def tinh_tb(arr): # arr: mảng chứa các giá trị cần tính trung bình
  sum=0
  for i in arr:
    sum+=i
  tb=sum/len(arr)
  return tb

- Xây dựng hàm tính giá trị trung vị

In [7]:
# Hàm tính giá trị trung vị
def tinh_tv(arr): # arr: mảng chứ các giá trị cần tính trung vị
  if len(arr)%2!=0:
    valutv=arr[int((len(arr)-1)/2)]
    return valutv
  if len(arr)%2==0:
    valutv=(arr[int(len(arr)/2)]+arr[int(len(arr)/2-1)])/2
    return valutv

- Xây dựng hàm tính giá trị yếu vị

In [49]:
# Hàm tính giá trị yếu vị
def tinh_yv(arr): # arr: mảng chứa các giá trị cần tính yếu vị
  dic={}  # Chứa các giá trị và tần số  xuất hiện của nó
  # Kiểm tra tần số lặp lại của từng phần tử
  for i in range(0,len(arr)):
    count=0 # đếm tần số xuất hiện
    for j in range(i,len(arr)):
      if arr[i]==arr[j]:
        count+=1  
    dic.setdefault(arr[i],count)
  #  Xuất giá trị yếu vị:
  if max(dic.values())==1:
      print("Không có giá trị yếu vị!!")
  else:
    for i,j in dic.items():
      if j == max(dic.values()) :
        print(" Giá trị yếu vị: ",i)
  
    

- Xây dựng hàm tính phương sai


Phương sai được tính bằng cách xác định giá trị chênh lệch giữa mỗi số trong tập dữ liệu với giá trị trung bình, sau đó bình phương các chênh lệch nhằm cho chúng mang giá trị dương và không triệt tiêu lẫn nhau. Cuối cùng chia tổng số lượng quan sát trong tập dữ liệu.

In [6]:
def tinh_ps(arr): # arr: mảng chứa các giá trị cần tính phương sai
  # Gọi hàm tính trung bình
  tb=tinh_tb(arr)
  # Tính phương sai
  sum_bp=0 # Tổng bình phương
  # Tính tổng các bình phương giá trị chênh lệch
  for i in arr:
    sum_bp+=(i-tb)**2
  # Tính phương sai
  ps=sum_bp/len(arr)
  return ps


- Xây dựng hàm tính độ lệch chuẩn


In [12]:
def tinh_dlc(arr): 
  # Gọi hàm tính phương sai
  ps=tinh_ps(arr)
  dlc=ps**0.5
  return dlc


- Tạo ra ma trận $A_{10\times15}$ với các giá trị sinh bởi hàm arrange()


In [17]:
# Tạo ma trận A(10x15):
import numpy as np
A=np.arange(0,150).reshape((10,15))
print("Ma trận A:\n",A)

Ma trận A:
 [[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]]


- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A

In [51]:
# Áp dụng hàm tính trung bính:
print("Kết quả hàm tính trung bình theo hàng: ")
print(np.apply_along_axis(tinh_tb,1,A))

Kết quả hàm tính trung bình theo hàng: 
[  7.  22.  37.  52.  67.  82.  97. 112. 127. 142.]


In [52]:
# Áp dụng hàm tính trung vị:
print("Kết quả hàm tính trung vị theo hàng: ")
print(np.apply_along_axis(tinh_tv,1,A))

Kết quả hàm tính trung vị theo hàng: 
[  7  22  37  52  67  82  97 112 127 142]


In [53]:
# Áp dụng hàm tính yếu vị:
print("Kết quả hàm tính yếu vị theo hàng: ")
print(np.apply_along_axis(tinh_yv,1,A))

Kết quả hàm tính yếu vị theo hàng: 
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
[None None None None None None None None None None]


In [61]:
# Áp dụng hàm tính phương sai:
print("Kết quả hàm tính phương sai theo hàng: ")
print(np.apply_along_axis(tinh_ps,1,A))

Kết quả hàm tính phương sai theo hàng: 
[18.66666667 18.66666667 18.66666667 18.66666667 18.66666667 18.66666667
 18.66666667 18.66666667 18.66666667 18.66666667]


In [56]:
# Áp dụng hàm tính độ lệch chuẩn:
print("Kết quả hàm tính độ lệch chuẩn theo hàng: ")
print(np.apply_along_axis(tinh_dlc,1,A))

Kết quả hàm tính độ lệch chuẩn theo hàng: 
[4.3204938 4.3204938 4.3204938 4.3204938 4.3204938 4.3204938 4.3204938
 4.3204938 4.3204938 4.3204938]


- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [57]:
# Áp dụng hàm tính trung bính:
print("Kết quả hàm tính trung bình theo cột: ")
print(np.apply_along_axis(tinh_tb,0,A))

Kết quả hàm tính trung bình theo cột: 
[67.5 68.5 69.5 70.5 71.5 72.5 73.5 74.5 75.5 76.5 77.5 78.5 79.5 80.5
 81.5]


In [58]:
# Áp dụng hàm tính trung vị:
print("Kết quả hàm tính trung vị theo cột: ")
print(np.apply_along_axis(tinh_tv,0,A))

Kết quả hàm tính trung vị theo cột: 
[67.5 68.5 69.5 70.5 71.5 72.5 73.5 74.5 75.5 76.5 77.5 78.5 79.5 80.5
 81.5]


In [59]:
# Áp dụng hàm tính yếu vị:
print("Kết quả hàm tính yếu vị theo cột: ")
print(np.apply_along_axis(tinh_yv,0,A))

Kết quả hàm tính yếu vị theo cột: 
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
Không có giá trị yếu vị!!
[None None None None None None None None None None None None None None
 None]


In [60]:
# Áp dụng hàm tính phương sai :
print("Kết quả hàm tính phương sai theo cột: ")
print(np.apply_along_axis(tinh_ps,0,A))

Kết quả hàm tính phương sai theo cột: 
[1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25
 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25]


In [62]:
# Áp dụng hàm tính độ lệch chuẩn:
print("Kết quả hàm tính độ lệch chuẩn theo cột: ")
print(np.apply_along_axis(tinh_dlc,0,A))

Kết quả hàm tính độ lệch chuẩn theo cột: 
[43.08421985 43.08421985 43.08421985 43.08421985 43.08421985 43.08421985
 43.08421985 43.08421985 43.08421985 43.08421985 43.08421985 43.08421985
 43.08421985 43.08421985 43.08421985]
