<a href="https://colab.research.google.com/github/NguyenTanTan/Bai-tap-python/blob/python/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [8]:
import numpy as np
import scipy.stats as st

In [9]:
samples_1=np.arange(-15,27,0.7)
samples_1

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [70]:

samples_2=np.random.normal(2.7,1.2,40)
samples_2



array([1.99940131, 2.60088841, 1.36322695, 1.2017716 , 2.76901797,
       1.0600632 , 2.90514965, 3.9279937 , 4.04439333, 3.32102639,
       3.230023  , 2.89828167, 1.8999493 , 0.39061855, 2.9541245 ,
       2.5559751 , 1.61383732, 4.47729516, 3.61110673, 3.86769411,
       1.56498339, 3.17972055, 3.7341703 , 2.62499069, 5.28198032,
       2.30740676, 0.88239503, 0.75286788, 2.91422224, 3.17125754,
       3.71941564, 2.12781089, 2.81418108, 0.55235785, 3.23020488,
       2.48823862, 3.37725616, 2.04098485, 2.69334473, 2.39059576])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [67]:
samples_3=np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'],17) 
samples_3

array(['Britain', 'France', 'Viet Nam', 'France', 'Russia', 'Singapore',
       'France', 'Singapore', 'Singapore', 'Britain', 'Britain',
       'Singapore', 'Britain', 'Viet Nam', 'Viet Nam', 'France', 'Russia'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [58]:
samples_4=np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'],17,p=[0.3,0.2,0.2,0.2,0.1]) 
samples_4


array(['Viet Nam', 'Russia', 'Britain', 'Britain', 'Russia', 'Russia',
       'Britain', 'Singapore', 'Britain', 'Russia', 'Viet Nam', 'Britain',
       'Russia', 'Singapore', 'Viet Nam', 'Britain', 'Russia'],
      dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [69]:

samples_5=st.norm.rvs(12.7,2.6,30)
samples_5

array([10.06158037, 16.45935091, 11.01466446, 12.11797162, 19.41783716,
       14.46475471, 14.33974337,  6.89179717, 11.52575069, 13.52198549,
       16.63625854, 13.85114656, 12.2139931 , 12.74968618, 11.28053714,
       12.89648766, 10.09074186, 12.53033855,  9.41480493, 12.05057164,
       12.5477969 , 15.50383996, 10.82911311, 11.76001726, 11.31706369,
       10.55166488, 12.63925171, 12.76990196,  8.846648  , 10.77065089])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

mean=10
std=5
size=20

In [71]:
# Cách 2
samples_6=st.poisson.rvs(10,5,20)
samples_6

array([17, 12, 12, 20, 10, 16, 15, 22, 14, 12, 15, 11, 11, 13, 16, 12, 15,
       20, 16, 12])