<a href="https://colab.research.google.com/github/NguyenTanTan/Bai-tap-python/blob/python/NUMPY_C%C3%A1c_h%C3%A0m_To%C3%A1n_h%E1%BB%8Dc_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian R3 , một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
arr1=np.array((5,7,14))
print(arr1)

[ 5  7 14]


Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong 
không gian 15 chiều này bằng Numpy.

In [ ]:
arr2=np.array((1,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15))
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Trong không gian Rn

, xét vector OA⃗⃗⃗⃗⃗ , với O là điểm gốc tọa độ và A là điểm có tọa độ tổng
quát là (a1, a2, ..., an). Vector OA⃗⃗⃗⃗⃗ lúc này được viết dưới dạng vector cột (column vector) là:

OA⃗⃗⃗⃗⃗ = [
a1
a2
⋮
an
]

Hay ở dạng vector hàng (row vector) là:
OA⃗⃗⃗⃗⃗ = [
a1
a2
⋮
an
]
T
= [a1 a2 ... an]

Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương
được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.


In [ ]:
# Nhập số chiều của không gian
n=int(input(" Nhập số chiều của không gian: "))
while n <= 0:
  n= int(input(" Nhập lại số nguyên dương n: "))
import random
import numpy as np
# Sinh ngẫu nhiên vector
OA=np.array([random.randint(0,99) for i in range(0,n)])
print(OA)


 Nhập số chiều của không gian: 3
[ 6 35 86]


Bài 4: Trong không gian R3

, xét vector OA⃗⃗⃗⃗⃗
OA⃗⃗⃗⃗⃗ = [
7
−5
8
]

Hãy viết chương trình tính chiều dài của vector OA⃗⃗⃗⃗⃗ , biết công thức tổng quát để tính chiều dài
vector OA⃗⃗⃗⃗⃗ trong không gian Rn
là:
‖OA⃗⃗⃗⃗⃗ ‖ = √a1
2 + a2
2 + ⋯ + an
2

Lưu ý: sử dụng Numpy




In [ ]:
OA=np.array((7,-5,8)) # Tạo vector OA
# Chiều dài vector OA:
cd=np.linalg.norm(OA)
print( " Chiều dài OA: ", cd)

 Chiều dài OA:  11.74734012447073


Bài 5: Trong không gian Rn

, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB⃗⃗⃗⃗⃗ và tính

chiều dài của vector này ‖AB⃗⃗⃗⃗⃗ ‖. Lưu ý: sử dụng Numpy.

In [ ]:
# Số chiều của 2 điểm A,B:
n==int(input(" Số chiều của 2 điểm A, B: "))
while n <= 0:
  n= int(input(" Nhập lại số nguyên dương n: "))
# Sinh ngẫu nhiên 2 điểm:
a=[random.randint(0,10) for i in range(0,n)]
b=[random.randint(0,10) for i in range(0,n)]
A= np.array(a)
B= np.array(b)
print( A, B)
# Vector AB:
AB=B-A
print(AB)
# Chiều dài:
CDai=np.linalg.norm(AB)
print(" Chiều dài AB là: ", CDai)  

 Số chiều của 2 điểm A, B: 4
[ 8 10  4  0] [ 4 10  8  5]
[-4  0  4  5]
 Chiều dài AB là:  7.54983443527075


Bài 6: Tích vô hướng của 2 vector a & b⃗ (dot product hoặc inner product hoặc scalar product) được
tính theo công thức tổng quát là:

a ∙ b⃗ = a1b1 + a2b2 + ⋯ + anbn

Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b⃗ và tính tích vô hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.inner()

In [4]:
import random
import numpy as np
# Nhập số chiều không gian:
n = int(input(" Nhập số chiều: "))
while n <= 0:
  n= int(input(" Nhập lại số nguyên dương n: "))
# Sinh ngẫu nhiên 2 vector:
vec1=np.array([ random.randint(0,99) for i in range (0,n)])
vec2=np.array([ random.randint(0,99) for i in range (0,n)])
print(vec1,vec2)
# Tích vô hướng 2 vector
tvh=np.dot(vec1,vec2)
print(" Tích vô hướng: ",tvh)



 Nhập số chiều: 2
[78  9] [89 11]
7041


Bài 7: Tích hữu hướng (cross product) của 2 vector a & b⃗ được tính theo công thức tổng quát là:

a × b⃗ = ‖a ‖‖b⃗ ‖ sin(θ)

Trong không gian Rn , hãy sinh ngẫu nhiên 2 vector a & b⃗ và tính tích hữu hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích hữu hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.cross()

In [5]:
import random
import numpy as np
# Nhập số chiều không gian:
n = int(input(" Nhập số chiều: "))
while n <= 0:
  n= int(input(" Nhập lại số nguyên dương n: "))
# Sinh ngẫu nhiên 2 vector:
veca=np.array([ random.randint(0,99) for i in range (0,n)])
vecb=np.array([ random.randint(0,99) for i in range (0,n)])
print(veca,vecb)
# Tích hữu hướng 2 vector a,b: 
thh= np.cross(veca,vecb)
print(" Tích hữu hướng : ", thh)


 Nhập số chiều: 3
[31 51 68] [78 22 78]
[ 2482  2886 -3296]


Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được
thực hiện thông qua thao tác a.T
Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn , số nguyên dương n
được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a .

In [14]:
import random
import numpy as np
# Nhập số chiều không gian:
n = int(input(" Nhập số chiều: "))
while n <= 0:
  n= int(input(" Nhập lại số nguyên dương n: "))
# Sinh ngẫu nhiên 1 vector:
vec=np.array([ random.randint(0,99) for i in range (0,n)])
print(" Vecto sinh ngẫu nhiên: ",vec)

# Chuyển vị vecto:
print(vec.T)


 Nhập số chiều: 4
 Vecto sinh ngẫu nhiên:  [85 38  9 39]
[85 38  9 39]


Bài 9 - Kết hợp cấu trúc list với Numpy: Xét 2 cấu trúc list dưới đây:
1. a = [1, 2, 3, 4, 5]
2. b = [[1], [2], [3], [4], [5]]
Hãy:
 Xuất a và b ra màn hình
 Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
 Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [24]:
# Tạo vector, mảng:
import numpy as np
a= np.array([1,2,3,4,5])
print(a)
b= np.array([[1],[2],[3],[4],[5]])
print(b)
# Chuyển vị hai vector:
print(" Chuyển vị vector a: ", a.T)
print(" Chuyển vị vector b: ", b.T)



[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
 Chuyển vị vector a:  [1 2 3 4 5]
 Chuyển vị vector b:  [[1 2 3 4 5]]


Bài 10: Trong không gian Rn

, hãy sinh ngẫu nhiên vector a và b⃗ , n là số nguyên dương nhập vào

từ bàn phím. Hãy:
 Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình
 Thực hiện phép cộng 2 vector: a + b⃗ và xuất kết quả ra màn hình.

In [27]:
import random
import numpy as np
# Nhập số chiều không gian:
n = int(input(" Nhập số chiều: "))
while n <= 0:
  n= int(input(" Nhập lại số nguyên dương n: "))
# Sinh ngẫu nhiên 2 vector:
vec_a=np.array([ random.randint(0,99) for i in range (0,n)])
vec_b=np.array([ random.randint(0,99) for i in range (0,n)])
print(vec_a,vec_b)
# Nhân vecto a với m
m=int(input(" Nhập giá trị của m: "))
print("Kết quả của phép nhân vecto: ",vec_a*m )
# Cộng 2 vecto:
print(" Kết quả cộng 2 vecto: ", vec_a+vec_b)

 Nhập số chiều: 4
[91 43 99 23] [32 79 90 41]
 Nhập giá trị của m: 2
Kết quả của phép nhân vecto:  [182  86 198  46]
 Kết quả cộng 2 vecto:  [123 122 189  64]
